name = "Quante"
uuid = "cffb2240-8e2b-11e9-2857-d3cff796b0cb"
authors = ["Jarvist Moore Frost <jarvist@gmail.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
